### ISSUE TITLE
A bug in /util/dl_data.sh download script

### ISSUE THREAD

**Issue by shaprann** [PatrickTUM/SEN12MS-CR-TS#1]
I've found a small bug in your download script at [line 284](https://github.com/PatrickTUM/SEN12MS-CR-TS/blob/master/util/dl_data.sh#L284). The script effectively only executes `wget` with `-O $filename$` and not with `-P $dl_extract_to -O $filename` as expected, which is because of [this strange behavior of wget](https://unix.stackexchange.com/questions/244404/wget-p-o-together-does-not-work). 

Thus, the file is downloaded into the current directory and not into `$dl_extract_to`, and tar throws a "file not found" error for `$dl_extract_to'/'$filename`, because the file is not there.

A fix would be to `wget` the file using `-O $dl_extract_to'/'$filename` at line 284. I tested it and it works.

**Comment by PatrickTUM** [comment]
Thanks, good catch! I updated the script accordingly. This way, the args to `wget` are also more consistent to the usage of `tar` in [L285](https://github.com/PatrickTUM/SEN12MS-CR-TS/blob/abebe06ace68c34750285a27679a7b8eb305b4c5/util/dl_data.sh#L285).
