### ISSUE TITLE
Cannot find pre-trained models

### ISSUE THREAD

**Issue by SpectorSong** [PatrickTUM/SEN12MS-CR-TS#10]
Thank you for sharing this code, its very useful. I want to download the pre-trained models, but I noticed that the links are "Not Found".
(For example, the resnet model: https://syncandshare.lrz.de/dl/fiFfN2bj6DaFXfGEGAaAvdZE/baseline_resnet.pth)
Could you please share these models again? Thank you again.

**Comment by PatrickTUM** [comment]
Dear @SpectorSong,

thanks for pointing this out to me! Please try again, the files are on a new host and the issue should be resolved now.
I've graduated at TUM a few months ago and the associate file hosting service ended their offer. Subsequently, I retrieved the files, put them on a new platform and updated the repositories & websites accordingly. Closing this issue, but feel free to reopen in case pCloud shouldn't be accessible for everyone.

**Comment by SpectorSong** [comment]
> Dear @SpectorSong,
> 
> thanks for pointing this out to me! Please try again, the files are on a new host and the issue should be resolved now. I've graduated at TUM a few months ago and the associate file hosting service ended their offer. Subsequently, I retrieved the files, put them on a new platform and updated the repositories & websites accordingly. Closing this issue, but feel free to reopen in case pCloud shouldn't be accessible for everyone.

Thank you, I can download them now. Best wishes!
