### ISSUE TITLE
Question about SEN12MS-CR-TS Size

### ISSUE THREAD

**Issue by Zhou-Hangyu** [PatrickTUM/SEN12MS-CR-TS#12]
Hi! Thanks for the amazing dataset! I followed the instructions and downloaded the entire dataset on my server. However, the total size is around 1.2TB, contradicting to the 2TB reported in your paper. Am I missing any data? Thank you!

**Comment by mondlichtpierrot** [comment]
Hi @Zhou-Hangyu,

good question! Combined in size, both SEN12MS-CR and SEN12MS-CR-TS together should be just a little more compact than the mentioned 2 TB. However, in case you wish to work with SEN12MS-CR-TS only, then it's gonna be smaller accordingly. Just make sure you fetched both the [train](https://mediatum.ub.tum.de/1639953) and the [test](https://mediatum.ub.tum.de/1659251) split. You can find more information [here](https://patricktum.github.io/cloud_removal/sen12mscrts/) and a convenient shell script for downloading everything right [here](https://github.com/PatrickTUM/SEN12MS-CR-TS/blob/master/util/dl_data.sh). Hoping this helps you!

Cheers,
Patrick

**Comment by mondlichtpierrot** [comment]
Hi @Zhou-Hangyu,

good question! Combined in size, both SEN12MS-CR and SEN12MS-CR-TS together should be just a little more compact than the mentioned 2 TB. However, in case you wish to work with SEN12MS-CR-TS only, then it's gonna be smaller accordingly. Just make sure you fetched both the [train](https://mediatum.ub.tum.de/1639953) and the [test](https://mediatum.ub.tum.de/1659251) split. You can find more information [here](https://patricktum.github.io/cloud_removal/sen12mscrts/) and a convenient shell script for downloading everything right [here](https://github.com/PatrickTUM/SEN12MS-CR-TS/blob/master/util/dl_data.sh). Hoping this helps you!

Cheers,
Patrick
