### ISSUE TITLE
How to test the pretrained model on SEN12MS-CR dataset?

### ISSUE THREAD

**Issue by HuangxingLin123** [PatrickTUM/SEN12MS-CR-TS#3]

**Comment by PatrickTUM** [comment]
Hi @HuangxingLin123,

great to see you interested in our datasets! The focus of this repository is on the multi-temporal SEN12MS-CR-TS dataset, and you may test pretrained models on it via

`python test.py --dataroot /path/to/sen12mscrts --dataset_mode sen12mscrts --results_dir /path/to/results --checkpoints_dir /path/to/results --name exemplary_training_run --model temporal_branched --netG resnet3d_9blocks_withoutBottleneck --include_S1 --input_nc 15 --output_nc 13 --sample_type cloudy_cloudfree --cloud_masks s2cloudless_mask --input_type test --max_dataset_size 100000 --num_test 100000 --n_input_samples 3 --epoch latest --eval --phase test --alter_initial_model --initial_model_path /path/to/models/baseline_resnet.pth --min_cov 0.0 --max_cov 1.0 --region all`

with the pretrained CR-TS Net checkpoints you may find [here](https://patricktum.github.io/cloud_removal/sen12mscrts/).
If you want to write your own evaluation scripts, you may use the SEN12MS-CR-TS dataloader as a starting point:

```python
import torch
from data.dataLoader import SEN12MSCRTS
dir_SEN12MSCRTS = '/path/to/your/SEN12MSCRTS'
sen12mscrts     = SEN12MSCRTS(dir_SEN12MSCRTS, split='all', region='all', n_input_samples=3)
dataloader      = torch.utils.data.DataLoader(sen12mscrts)

for pdx, samples in enumerate(dataloader): print(samples['input'].keys())
```

Alternatively, you can in a similar manner iterate over the [SEN12MS-CR dataloader](https://github.com/PatrickTUM/SEN12MS-CR-TS/blob/abebe06ace68c34750285a27679a7b8eb305b4c5/data/dataLoader.py#L372) of our mono-temporal dataset. The focus of this repository is on multi-temporal cloud removal and a multi-temporal model. But if you wish to see some exemplary use case of a mono-temporal model on our mono-temporal dataset, please have a look at my colleague Fang's repository of [GLF-CR](https://github.com/xufangchn/GLF-CR)! 

Hoping this helps you! I'll close the issue for now, but feel free to re-open it for any follow-up questions.

Cheers,
Patrick
