### ISSUE TITLE
A question about the SEN12MSCR dataset

### ISSUE THREAD

**Issue by chuanchuan-qin** [PatrickTUM/SEN12MS-CR-TS#5]
Hello @PatrickTUM,

I downloaded the SEN12MSCR dataset for cloud removal tasks. I can understand that s1 has 2 channels and s2_cloudy has 13 channels, but I don't understand why s2 has 13 channels. Why not use the rgb channel directly, which can also reduce the amount of calculation.

**Comment by PatrickTUM** [comment]
Hi @chuanchuan-qin, 

great seeing you interested in our work! In brief: restoring all 13 channels of information ensures that the cloud-removed data is compatible with any further downstream applications that a remote sensing practitioner may be commonly interested in. For sure, if your main interest is solely in visualization then the RGB bands are sufficient. But oftentimes, engineers and researchers wish to calculate indices or products relying on further spectral information. See [here](https://custom-scripts.sentinel-hub.com/custom-scripts/sentinel/sentinel-2/) for a brief overview or [here](https://elib.dlr.de/186738/) for a specific example of applying a scene classification downstream task on the entirety of reconstructed information. Hoping this clarifies our motivation, cheers.
