### ISSUE TITLE
train data ist not accessible

### ISSUE THREAD

**Issue by hwuebben** [PatrickTUM/SEN12MS-CR-TS#6]
As title states, can't access the training split.
best regards

**Comment by PatrickTUM** [comment]
Dear @hwuebben,

can you access the training data as of now, or does this issue persist for you? If so, how did you attempt to access the data?
I encountered no problems accessing the [train](https://mediatum.ub.tum.de/1639953) and [test](https://mediatum.ub.tum.de/1659251) split data of SEN12MS-CR-TS, as of now. Feel free to reopen the issue if there's still need, so we can try to reproduce the challenges you encountered. Cheers, Patrick
