### ISSUE TITLE
Location of tif2hdf5.py

### ISSUE THREAD

**Issue by kvantricht** [PatrickTUM/SEN12MS-CR-TS#9]
Hi there,

I'm trying to replicate the conversion of the dataset to hdf5, but as per [this line](https://github.com/PatrickTUM/SEN12MS-CR-TS/blob/7e06a43449cb053178d13c6442d41c609cc5dafc/util/hdf5converter/script_tif2hdf5.sh#L11C8-L11C19) I don't seem to be able to find where the referenced script is located.

**Comment by PatrickTUM** [comment]
Dear @kvantricht,

thanks for making me aware of this issue. In fact, I never utilized the converter myself and eventually the related file may have been left out somehow. As @stuckerc was the original author and use of the conversion scripts, I'll kindly ask her whether she may by chance still have access to the missing file.

**Comment by PatrickTUM** [comment]
Hey @kvantricht,

@stuckerc kindly provided me with the file that was initially missing and with the latest commit you may find it [here](https://github.com/PatrickTUM/SEN12MS-CR-TS/blob/master/util/hdf5converter/tif2hdf5.py). I must however say that I currently don't have the capacities to test run it, and the file may have been originally developed a few commits ago. So you may eventually have to adapt this slightly to your needs. I'll close the issue for now, but would gladly accept your pull request.

Cheers,
Patrick
